### ISSUE TITLE
Add differentiation between files and directories in lathe file outputs

### ISSUE THREAD

**Issue by evergreen700** [bmeg/lathe#3]
Snakemake will throw an error if it expects to generate a file but generates a directory instead. It requires the syntax directory("path/to/directory") in place of the normal "file-name" when defining outputs for rules. (Input isn't as sensitive so no issues there). Some lathe download.yaml files on bmeg-etl like transform/pubmed/download.py have directories for outputs instead of files, so lathe being able to differentiate between the two is important.

**Comment by kellrott** [comment]
Moving away from snakemake
